spring:
  data:
    mongodb:
      database: Lib
      port: 27017
      host: localhost
      authentication-database: admin
banner:
  location: banner.txt

logging:
  level:
    org.springframework: INFO

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.changeLog