spring:
  banner:
    location: banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        enable_lazy_load_no_trans: true
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,logfile
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
logging:
  file:
    name: "logs/application.log"